config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurant#index'
  resources :restaurants do
    resources :reviews, only: [ :index, :new, :create ]
  end
  resources :reviews, only: [ :show, :edit ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def create
    @restaurant = Restaurant.new(restau_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restau_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = restaurant
    if @review.save
      redirect_to restaurant_path(restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
Restaurants
<ul>
<% @restaurants.each do |restau| %>
  <li>
    <%= link_to restau.name, restaurant_path(restau) %>
  </li>
<% end %>
</ul>
<%= link_to "Create a restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: ["italian", "belgian", "french", "japanese", "chinese"] %>
  <%= f.submit "Add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
Restaurant
<ul>
  <li><%= @restaurant.name %></li>
  <li><%= @restaurant.address %></li>
  <li><%= @restaurant.category %></li>
</ul>
Reviews
<ul>
<% @reviews.each do |rev| %>
  <hr>
  <li><%= rev.content %></li>
  <li><%= rev.rating %></li>
<% end %>
</ul>
<%= link_to "Create a review", new_restaurant_review_path(@restaurant) %>
<%= link_to "Back to list", restaurants_path %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant,@review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>